apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Testando Nomes Ç
  description: API Description.
  tags:
    - go
    - service
spec:
  type: service
  lifecycle: production
  owner: team
